apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: private-registry
  namespace: scf
spec:
  secretName: bits-cert
  dnsNames:
  - registry.app.$DOMAIN
  acme:  
    config:
      - dns01:
          provider: dns
        domains:
          - registry.app.$DOMAIN
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer